---
title: "Wine Wall"
author: "Jason Taylor"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
    includes:
#      after_body: footer.html
  html_document: 
    fig_caption: yes
    fig_height: 6
    fig_width: 8
    highlight: textmate
---

Deminsions of the space 89.5" wide x 108" high

Wood is 2.5" wide and lengths are 36", 48", 60"

```{r libraries, include = FALSE, message = FALSE, results = FALSE}
library.list <- c("tidyverse", "ggtextures")
lapply(library.list, require, character.only = TRUE)
```

```{r}
set.seed(42)
width <- 89.5
height <- 108

board_width <- 2.5

num_boards_w <- round(width / board_width, digits = 0)
```

```{r}
slot <- sort(rep(1:num_boards_w, 3))
spot <- rep(c("bottom", "middle", "top"), 12)
len <- rep(c(3, 3, 3, 4, 5, NA, 5, 4, NA), 12)

layout <- data.frame(cbind(slot, spot, len),
                     stringsAsFactors = FALSE) %>%
  mutate(slot = as.numeric(slot), 
         len = as.numeric(len)) %>%
  filter(complete.cases(.))

layout$stain <- as.character(sample(1:2, size = nrow(layout), replace = TRUE))

layout <- mutate(layout, image_file = case_when(stain == "1" ~ "walnut.png",
                                                TRUE ~ "espresso.png"))
```

```{r}
ggplot(layout, aes(x = slot, y = len, image = image_file, group = spot)) +
  ggtextures::geom_textured_col(width = 1) + 
  scale_y_continuous(breaks = seq(0, 9, 3),
                     labels = scales::dollar_format(suffix = "ft", prefix = "")) +
  scale_x_continuous(breaks = seq(0, num_boards_w, 6)) +
  labs(x = "Slot", y = "Wall Position") +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        legend.title = element_blank()) +
  theme(axis.line = element_line(size = 1, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5, size = 14,
                                  family = "Tahoma", face = "bold"),
        text = element_text(family = "Tahoma"),
        axis.text.x = element_text(colour = "black", size = 10),
        axis.text.y = element_text(colour = "black", size = 10)) +
  ggtitle("Wine Room Interior Wall")
```

